### ISSUE TITLE
Publish release metadata 

### ISSUE THREAD

**Issue by tcarreira** [tsuru/tsuru-client#177]
goreleaser already builds a `dist/metadata.json` but it is not published by default:

```json
{
  "project_name": "tsuru",
  "tag": "1.12.0",
  "previous_tag": "1.10.4",
  "version": "1.12.0",
  "commit": "d5de5fa8564ea2ee4de0ded3d496f68560112a1b",
  "date": "2022-09-12T13:52:15.108848116Z",
  "runtime": {
    "goos": "linux",
    "goarch": "amd64"
  }
}
```

[Goreleaser documentation](https://goreleaser.com/customization/release/) has instructions on how to publish extra files using the release directive:

```yaml
# .goreleaser.yaml
release:
  extra_files:
    - glob: dist/metadata.json

```
